package com.webcommands.http;

import java.time.Instant;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Manages one-time connect tokens generated by /webcommands genlink.
 * Each token is valid for 15 minutes and can only be redeemed once.
 */
public class ConnectTokenManager {

    private static final long TTL_SECONDS = 15 * 60; // 15 minutes

    private record TokenEntry(Instant createdAt, boolean used) {}

    private static final ConcurrentHashMap<String, TokenEntry> tokens = new ConcurrentHashMap<>();

    private ConnectTokenManager() {}

    /** Generates a new single-use token and stores it. Returns the token string. */
    public static String generate() {
        purgeExpired();
        String token = UUID.randomUUID().toString();
        tokens.put(token, new TokenEntry(Instant.now(), false));
        return token;
    }

    /**
     * Attempts to redeem a token.
     * Returns true if the token exists, has not been used, and has not expired.
     * Marks the token as used on success.
     */
    public static boolean redeem(String token) {
        TokenEntry entry = tokens.get(token);
        if (entry == null) return false;
        if (entry.used()) return false;
        if (Instant.now().isAfter(entry.createdAt().plusSeconds(TTL_SECONDS))) {
            tokens.remove(token);
            return false;
        }
        tokens.put(token, new TokenEntry(entry.createdAt(), true));
        return true;
    }

    /** Removes expired tokens to prevent unbounded growth. */
    private static void purgeExpired() {
        Instant cutoff = Instant.now().minusSeconds(TTL_SECONDS);
        tokens.entrySet().removeIf(e -> e.getValue().createdAt().isBefore(cutoff));
    }
}
