package com.webcommands.http.handlers;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.webcommands.http.ConnectTokenManager;
import com.webcommands.http.CorsHelper;

import java.io.IOException;
import java.nio.charset.StandardCharsets;

/** POST /api/redeem — validates a one-time connect token generated by /webcommands genlink. */
public class RedeemHandler implements HttpHandler {

    private final String allowedOrigin;

    public RedeemHandler(String allowedOrigin) {
        this.allowedOrigin = allowedOrigin;
    }

    @Override
    public void handle(HttpExchange exchange) throws IOException {
        if (CorsHelper.handlePreflight(exchange, allowedOrigin)) return;
        CorsHelper.addCorsHeaders(exchange, allowedOrigin);

        if (!"POST".equalsIgnoreCase(exchange.getRequestMethod())) {
            CorsHelper.sendError(exchange, 405, "Method Not Allowed");
            return;
        }

        try {
            String body = new String(exchange.getRequestBody().readAllBytes(), StandardCharsets.UTF_8);
            JsonObject req = JsonParser.parseString(body).getAsJsonObject();
            String token = req.get("token").getAsString();

            if (ConnectTokenManager.redeem(token)) {
                CorsHelper.sendJson(exchange, 200, "{\"ok\":true}");
            } else {
                CorsHelper.sendJson(exchange, 200, "{\"ok\":false,\"error\":\"Token invalido, ya usado o expirado\"}");
            }
        } catch (Exception e) {
            CorsHelper.sendError(exchange, 400, "Bad Request");
        }
    }
}
