package com.webcommands;

import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.context.CommandContext;
import com.webcommands.config.ModConfig;
import com.webcommands.http.ConnectTokenManager;
import com.webcommands.http.WebServer;
import com.webcommands.rules.RulesManager;
import com.webcommands.scanner.CommandScanner;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;
import net.minecraft.network.chat.Component;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.CommandEvent;
import net.minecraftforge.event.RegisterCommandsEvent;
import net.minecraftforge.event.server.ServerStartedEvent;
import net.minecraftforge.event.server.ServerStoppingEvent;
import net.minecraftforge.eventbus.api.EventPriority;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.ModLoadingContext;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.config.ModConfig.Type;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.nio.charset.StandardCharsets;
import java.util.Base64;

@Mod(WebCommandsMod.MODID)
public class WebCommandsMod {

    public static final String MODID = "webcommands";
    public static final Logger LOGGER = LogManager.getLogger(MODID);

    private CommandDispatcher<CommandSourceStack> lastDispatcher = null;

    public WebCommandsMod() {
        ModLoadingContext.get().registerConfig(Type.COMMON, ModConfig.SPEC, "webcommands-common.toml");
        MinecraftForge.EVENT_BUS.register(this);
        LOGGER.info("[webcommands] Mod loaded — waiting for server start.");
    }

    @SubscribeEvent(priority = EventPriority.LOW)
    public void onRegisterCommands(RegisterCommandsEvent event) {
        // Register /webcommands genlink (requires OP 4 or console)
        event.getDispatcher().register(
            Commands.literal("webcommands")
                .requires(src -> src.hasPermission(4))
                .then(Commands.literal("genlink")
                    .executes(WebCommandsMod::cmdGenLink))
        );
        lastDispatcher = event.getDispatcher();
        CommandScanner.tryUpdate(event.getDispatcher());
    }

    private static int cmdGenLink(CommandContext<CommandSourceStack> ctx) {
        String publicApiUrl = ModConfig.PUBLIC_API_URL.get().trim();

        if (publicApiUrl.isEmpty()) {
            ctx.getSource().sendFailure(Component.literal(
                "§c[WebCommands] Configura 'publicApiUrl' en webcommands-common.toml primero.\n" +
                "§7Ejemplo: publicApiUrl = \"http://123.45.67.89:8080\""
            ));
            return 0;
        }

        String token   = ConnectTokenManager.generate();
        String payload = publicApiUrl + "|" + token;
        String encoded = Base64.getUrlEncoder().withoutPadding()
            .encodeToString(payload.getBytes(StandardCharsets.UTF_8));

        ctx.getSource().sendSuccess(() -> Component.literal(
            "§a[WebCommands] §fCódigo de conexión §7(válido 15 min, uso único):\n" +
            "§e" + encoded + "\n" +
            "§7Cópialo y pégalo en la web para conectarte."
        ), true);

        LOGGER.info("[webcommands] Connect code generated by: {}", ctx.getSource().getTextName());
        return 1;
    }

    @SubscribeEvent
    public void onServerStarted(ServerStartedEvent event) {
        RulesManager.load();
        CommandScanner.ensureUpdated(lastDispatcher, event.getServer());
        WebServer.start(ModConfig.PORT.get(), ModConfig.ALLOWED_ORIGIN.get());
    }

    @SubscribeEvent
    public void onServerStopping(ServerStoppingEvent event) {
        WebServer.stop();
    }

    @SubscribeEvent
    public void onCommand(CommandEvent event) {
        RulesManager.enforce(event);
    }
}
